import type { FormConfig } from "@/types/forms";
import {
  PHONE_FIELD_ID,
  EMERGENCY_CONTACT_FIELD_ID,
  BLOOD_GROUP_FIELD_ID,
  AGE_GROUP_FIELD_ID,
} from "./discourse-fields";

export const formConfigs: FormConfig[] = [
  {
    id: "city-meetup-may-31",
    requiresPayment: true,
    title: "City Meetup Series",
    talkTitle: "Studying Undead Stars to Understand Theories of Physics",
    talkSpeaker: "Prof. Manjari Bagchi, IMSc",
    startTime: "2026-05-31T15:30:00",
    endTime: "2026-05-31T17:30:00",
    feeInfo: "INR 200 per head (venue charges split among all participants)",
    verifiedSuccess: {
      message: "Join the WhatsApp group using the link below. We will approve your WhatsApp group request within 2 hours of payment.",
      linkUrl: "https://chat.whatsapp.com/GNTShIlHUvlDY2fQIds4bR?mode=gi_t",
      linkLabel: "Join WhatsApp Group",
    },
    sheetTab: "May 31 Entries",
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number (used to add you to the WhatsApp group)",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "upiReferenceLast4",
        label: "Complete payment, then enter the last 4 digits of your transaction ID",
        helperText: "Pay INR 200 via UPI (scan QR or use the link). UPI ID: sivasubramanyamicici@ybl",
        helperLinkLabel: "Open UPI payment",
        helperLinkUrl: "upi://pay?pa=sivasubramanyamicici@ybl&pn=Sivasubramanyam&cu=INR&am=200",
        helperImageUrl: "/payment/phonepe-qr.png",
        helperImageAlt: "PhonePe QR code for SIVASUBRAMANYAM A",
        fullWidth: true,
        type: "text",
        required: true,
        validation: {
          pattern: "^\\d{4}$",
          message: "Enter exactly 4 digits",
        },
        placeholder: "e.g. 1234",
        section: "Payment Details",
      },
    ],
  },
  {
    id: "star-party-march-2026",
    requiresPayment: false,
    registrationClosesAt: "2026-03-08T00:00:00",
    title: "Star Party - March 2026",
    description: "Register your attendance for this month's star party. We are running a two night event on 13th and 14th March, so please specify which night(s) you will be joining. This will help us with logistics and planning.",
    // startTime: "2026-03-15T18:00:00",
    // endTime: "2026-03-15T21:00:00",
    sheetTab: "Entries",
    verifiedSuccess: {
      message: "As a regular participant, we are skipping the shortlist process for you. You can join the event WhatsApp group directly!",
      linkUrl: "https://chat.whatsapp.com/IpR00eMJfD8Cgc6Z54UJIc?mode=gi_t",
      linkLabel: "Join WhatsApp Group",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "age",
        label: "Age Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${AGE_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
        options: [
          { label: "Below 18", value: "Below 18" },
          { label: "18 - 25", value: "18-25" },
          { label: "26 - 35", value: "26-35" },
          { label: "36 - 50", value: "36-50" },
          { label: "51 - 65", value: "51-65" },
          { label: "Above 65", value: "Above 65" },
        ],
      },
      {
        name: "nights",
        label: "Which nights will you be joining?",
        type: "checkbox-group",
        required: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Night 1 — 13th March", value: "13 March" },
          { label: "Night 2 — 14th March", value: "14 March" },
        ],
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (12+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 20 },
        placeholder: "Enter 0 if no additional adults",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<12 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 20 },
        placeholder: "Enter 0 if no children",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "equipment",
        label: "Equipment that you will bring",
        type: "textarea",
        fullWidth: true,
        section: "Equipment Details",
        placeholder: "List any telescopes, binoculars, or other astronomy equipment you plan to bring...",
      },
      {
        name: "canBringCar",
        label: "Can you bring a car and offer carpooling to other participants?",
        type: "select",
        required: true,
        section: "Car Pooling",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "carSeats",
        label: "Number of seats available for other participants",
        type: "number",
        validation: { min: 1, max: 7 },
        placeholder: "How many people can you accommodate?",
        section: "Car Pooling",
        showWhen: { field: "canBringCar", value: "yes" },
      },
      {
        name: "location",
        label: "Where will you be coming from?",
        type: "text",
        required: true,
        placeholder: "Your locality in the city",
        section: "Car Pooling",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Person and Number",
        type: "text",
        required: true,
        discourseField: `user_fields.${EMERGENCY_CONTACT_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        placeholder: "Name & phone number",
        section: "Emergency Information",
      },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${BLOOD_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Emergency Information",
        options: [
          { label: "A+", value: "A+" },
          { label: "A-", value: "A-" },
          { label: "B+", value: "B+" },
          { label: "B-", value: "B-" },
          { label: "AB+", value: "AB+" },
          { label: "AB-", value: "AB-" },
          { label: "O+", value: "O+" },
          { label: "O-", value: "O-" },
        ],
      },
      {
        name: "observationalSkills",
        label: "Describe your observational skills and experience",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Tell us about your experience with astronomy and observation...",
      },
      {
        name: "eventReason",
        label: "Why do you want to attend this event?",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Share your motivation for attending...",
      },
      {
        name: "additionalQuestions",
        label: "Anything else that you would like to ask the CAC team?",
        type: "textarea",
        fullWidth: true,
        section: "Additional Questions",
        placeholder: "Any questions for us?",
      },
      {
        name: "conductCode",
        label: "I acknowledge that smoking, consuming alcohol and other anti-social behavior are strictly prohibited",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
      {
        name: "riskDisclaimer",
        label: "I understand and agree: Travelling by road involves inherent dangers including but not limited to accidents. CAC and its organizers are not responsible for any accidents or injuries during the event. CAC and organizers are not responsible for any loss or damage to personal property. I agree to take full responsibility.",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
    ],
  }, {
    id: "star-party-april-2026",
    requiresPayment: false,
    registrationClosesAt: "2026-03-29T00:00:00",
    title: "Star Party - April 2026",
    description: "Register your attendance for April's one-night star party on 11th April. AC rooms available; no individual beds; guests will need to share sleeping space; separate rooms for boys and girls. Adult cost: 1500; child cost: 1100.",
    sheetTab: "April Entries",
    verifiedSuccess: {
      message: "As a regular participant, we are skipping the shortlist process for you. You can join the event WhatsApp group directly!",
      linkUrl: "https://chat.whatsapp.com/LIwgncmAG3uFHVJnMF4zNl?mode=gi_t",
      linkLabel: "Join WhatsApp Group",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "age",
        label: "Age Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${AGE_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
        options: [
          { label: "Below 18", value: "Below 18" },
          { label: "18 - 25", value: "18-25" },
          { label: "26 - 35", value: "26-35" },
          { label: "36 - 50", value: "36-50" },
          { label: "51 - 65", value: "51-65" },
          { label: "Above 65", value: "Above 65" },
        ],
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (12+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 20 },
        placeholder: "Enter 0 if no additional adults",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<12 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 20 },
        placeholder: "Enter 0 if no children",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "equipment",
        label: "Equipment that you will bring",
        type: "textarea",
        fullWidth: true,
        section: "Equipment Details",
        placeholder: "List any telescopes, binoculars, or other astronomy equipment you plan to bring...",
      },
      {
        name: "canBringCar",
        label: "Can you bring a car and offer carpooling to other participants?",
        type: "select",
        required: true,
        section: "Car Pooling",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "carSeats",
        label: "Number of seats available for other participants",
        type: "number",
        validation: { min: 1, max: 7 },
        placeholder: "How many people can you accommodate?",
        section: "Car Pooling",
        showWhen: { field: "canBringCar", value: "yes" },
      },
      {
        name: "location",
        label: "Where will you be coming from?",
        type: "text",
        required: true,
        placeholder: "Your locality in the city",
        section: "Car Pooling",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Person and Number",
        type: "text",
        required: true,
        discourseField: `user_fields.${EMERGENCY_CONTACT_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        placeholder: "Name & phone number",
        section: "Emergency Information",
      },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${BLOOD_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Emergency Information",
        options: [
          { label: "A+", value: "A+" },
          { label: "A-", value: "A-" },
          { label: "B+", value: "B+" },
          { label: "B-", value: "B-" },
          { label: "AB+", value: "AB+" },
          { label: "AB-", value: "AB-" },
          { label: "O+", value: "O+" },
          { label: "O-", value: "O-" },
        ],
      },
      {
        name: "observationalSkills",
        label: "Describe your observational skills and experience",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Tell us about your experience with astronomy and observation...",
      },
      {
        name: "eventReason",
        label: "Why do you want to attend this event?",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Share your motivation for attending...",
      },
      {
        name: "additionalQuestions",
        label: "Anything else that you would like to ask the CAC team?",
        type: "textarea",
        fullWidth: true,
        section: "Additional Questions",
        placeholder: "Any questions for us?",
      },
      {
        name: "conductCode",
        label: "I acknowledge that smoking, consuming alcohol and other anti-social behavior are strictly prohibited",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
      {
        name: "riskDisclaimer",
        label: "I understand and agree: Travelling by road involves inherent dangers including but not limited to accidents. CAC and its organizers are not responsible for any accidents or injuries during the event. CAC and organizers are not responsible for any loss or damage to personal property. I agree to take full responsibility.",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
    ],
  },
  {
    id: "night-sky-passport-presale",
    requiresPayment: false,
    registrationClosesAt: "2026-05-27T00:00:00",
    title: "Night Sky Passport Presale Registration",
    description: "Register your presale request for Night Sky Passport book copies. This would help us plan the production and distribution of the book.",
    sheetTab: "Night Sky Passport Presale Entries",
    atLeastOneOf: {
      fields: ["adultCopies", "kidsCopies"],
      message: "Enter copies for adults or kids",
    },
    submitLabel: "Submit",
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Contact Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Contact Information",
      },
      {
        name: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Contact Information",
      },
      {
        name: "adultCopies",
        label: "Number of copies for adults (₹300 each)",
        type: "number",
        required: false,
        validation: { min: 0, max: 100 },
        section: "Presale Details",
        fullWidth: true,
      },
      {
        name: "kidsCopies",
        label: "Number of copies for kids (₹250 each)",
        type: "number",
        required: false,
        validation: { min: 0, max: 100 },
        section: "Presale Details",
        fullWidth: true,
      },
    ],
  }
];

export function getFormConfig(formId: string): FormConfig | undefined {
  return formConfigs.find((f) => f.id === formId);
}

export type RegistrationStatus = "not-yet-open" | "open" | "closed";

/**
 * Compute whether registration is currently open, not yet open, or closed
 * based on the form's registrationOpensAt / registrationClosesAt timestamps.
 * If neither is set, registration is always open.
 */
export function getRegistrationStatus(config: FormConfig): RegistrationStatus {
  const now = new Date();
  if (config.registrationOpensAt && new Date(config.registrationOpensAt) > now)
    return "not-yet-open";
  if (config.registrationClosesAt && new Date(config.registrationClosesAt) < now)
    return "closed";
  return "open";
}
