import type { FormConfig } from "@/types/forms";
import { parseIstDateTime } from "@/lib/datetime";
import {
  getRegistrationStatus as getWindowRegistrationStatus,
  isEventOver as isWindowEventOver,
  type RegistrationStatus,
} from "@/lib/registration-window";
import { FORM_REGISTRATION_WINDOWS } from "./registration-windows";
import {
  PHONE_FIELD_ID,
  EMERGENCY_CONTACT_FIELD_ID,
  BLOOD_GROUP_FIELD_ID,
  AGE_GROUP_FIELD_ID,
} from "./discourse-fields";

export type { RegistrationStatus };

export const formConfigs: FormConfig[] = [
  {
    id: "star-party-september-2026",
    ...FORM_REGISTRATION_WINDOWS["star-party-september-2026"],
    requiresPayment: false,
    skipCapacityCheck: true,
    title: "Star Party - September 2026",
    description:
      "Register your attendance for this month's star party on 12–13 September.\n\nParticipants will be shortlisted.",
    feeInfo:
      "Adults: ₹1300 (tentative)\nKids under 12: ₹1100 (tentative)\nWe are working to reduce this and will know in a day or two.",
    sheetTab: "September 12 Entries",
    additionalParticipants: {
      when: { field: "bringingParticipants", value: "yes" },
      adultField: "adultParticipants",
      kidField: "kidParticipants",
      maxAdults: 1,
      maxKids: 2,
      maxTotal: 3,
      messageBoth:
        "You can bring at most 1 additional adult and 2 children (4 people total including you).",
      messageNone: "Enter the number of additional participants you are bringing.",
      messageTooManyAdults: "You can bring at most 1 additional adult (2 adults total including you).",
      messageTooManyKids: "You can bring at most 2 additional children.",
    },
    verifiedSuccess: {
      message:
        "As a regular participant, we are skipping the shortlist process for you. You can join the event WhatsApp group directly!",
      linkUrl: "https://chat.whatsapp.com/Cjc8LrCfypkHA2podliZwX?mode=gi_t",
      linkLabel: "Join WhatsApp Group",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "age",
        label: "Age Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${AGE_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
        options: [
          { label: "Below 18", value: "Below 18" },
          { label: "18 - 25", value: "18-25" },
          { label: "26 - 35", value: "26-35" },
          { label: "36 - 50", value: "36-50" },
          { label: "51 - 65", value: "51-65" },
          { label: "Above 65", value: "Above 65" },
        ],
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        helperText: "Maximum 4 people per registration: 2 adults (including you) and 2 children.",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (12+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 1 },
        placeholder: "Enter 0 if no additional adults (max 1)",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<12 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 2 },
        placeholder: "Enter 0 if no children (max 2)",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "equipment",
        label: "Equipment that you will bring",
        type: "textarea",
        fullWidth: true,
        section: "Equipment Details",
        placeholder: "List any telescopes, binoculars, or other astronomy equipment you plan to bring...",
      },
      {
        name: "canBringCar",
        label: "Can you bring a car and offer carpooling to other participants?",
        type: "select",
        required: true,
        section: "Car Pooling",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "carSeats",
        label: "Number of seats available for other participants",
        type: "number",
        validation: { min: 1, max: 7 },
        placeholder: "How many people can you accommodate?",
        section: "Car Pooling",
        showWhen: { field: "canBringCar", value: "yes" },
      },
      {
        name: "location",
        label: "Where will you be coming from?",
        type: "text",
        required: true,
        placeholder: "Your locality in the city",
        section: "Car Pooling",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Person and Number",
        type: "text",
        required: true,
        discourseField: `user_fields.${EMERGENCY_CONTACT_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        placeholder: "Name & phone number",
        section: "Emergency Information",
      },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${BLOOD_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Emergency Information",
        options: [
          { label: "A+", value: "A+" },
          { label: "A-", value: "A-" },
          { label: "B+", value: "B+" },
          { label: "B-", value: "B-" },
          { label: "AB+", value: "AB+" },
          { label: "AB-", value: "AB-" },
          { label: "O+", value: "O+" },
          { label: "O-", value: "O-" },
        ],
      },
      {
        name: "observationalSkills",
        label: "Describe your observational skills and experience",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Tell us about your experience with astronomy and observation...",
      },
      {
        name: "eventReason",
        label: "Why do you want to attend this event?",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Share your motivation for attending...",
      },
      {
        name: "additionalQuestions",
        label: "Anything else that you would like to ask the CAC team?",
        type: "textarea",
        fullWidth: true,
        section: "Additional Questions",
        placeholder: "Any questions for us?",
      },
      {
        name: "conductCode",
        label: "I acknowledge that smoking, consuming alcohol and other anti-social behavior are strictly prohibited",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
      {
        name: "riskDisclaimer",
        label: "I understand and agree: Travelling by road involves inherent dangers including but not limited to accidents. CAC and its organizers are not responsible for any accidents or injuries during the event. CAC and organizers are not responsible for any loss or damage to personal property. I agree to take full responsibility.",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
    ],
  },
  {
    id: "city-meetup-august-30",
    ...FORM_REGISTRATION_WINDOWS["city-meetup-august-30"],
    allowGuestRegistration: true,
    allowsRegistrationWhitelist: true,
    requiresPayment: true,
    title: "City Meetup Series",
    talkTitle: "A Brief History of the Universe",
    talkSpeaker: "Prof. L. Sriramkumar",
    feeInfo: "Adults: ₹200\nKids under 16: Free",
    verifiedSuccess: {
      message: "Join the WhatsApp group using the link below. We will approve your WhatsApp group request within 2 hours of payment.",
      linkUrl: "https://chat.whatsapp.com/FYdsFuFcP5FBTMGpn0bz7y?s=cl&p=i&ilr=0",
      linkLabel: "Join WhatsApp Group",
    },
    sheetTab: "August 30 Entries",
    paymentPricing: {
      adultFee: 200,
      additionalAdultsField: "adultParticipants",
      bringingField: "bringingParticipants",
      bringingYesValue: "yes",
      includeRegistrant: true,
    },
    additionalParticipants: {
      when: { field: "bringingParticipants", value: "yes" },
      adultField: "adultParticipants",
      kidField: "kidParticipants",
      maxAdults: 1,
      maxKids: 2,
      maxTotal: 3,
      messageBoth:
        "You can bring at most 1 additional adult (2 adults total including you) and 2 children.",
      messageNone: "Enter the number of additional participants you are bringing.",
      messageTooManyAdults: "You can bring at most 1 additional adult (2 adults total including you).",
      messageTooManyKids: "You can bring at most 2 children.",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number (used to add you to the WhatsApp group)",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        helperText: "Maximum 2 adults (including you) and 2 children per registration.",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (16+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 1 },
        placeholder: "0 or 1",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<16 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 2 },
        placeholder: "0, 1, or 2",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "upiReferenceLast4",
        label: "Complete payment, then enter the last 4 digits of your transaction ID",
        helperText: "We're setting up a club payment gateway; until then this personal UPI is used. Pay via UPI (kids under 16 are free) — scan the QR code or copy the UPI ID below.",
        copyableValue: "sivasubramanyamicici@ybl",
        copyableLabel: "UPI ID",
        helperImageUrl: "/payment/phonepe-qr.png",
        helperImageAlt: "PhonePe QR code for SIVASUBRAMANYAM A",
        showPayableAmount: true,
        fullWidth: true,
        type: "text",
        required: true,
        validation: {
          pattern: "^\\d{4}$",
          message: "Enter exactly 4 digits",
        },
        placeholder: "e.g. 1234",
        section: "Payment Details",
      },
    ],
  },
  {
    id: "city-meetup-august-2",
    ...FORM_REGISTRATION_WINDOWS["city-meetup-august-2"],
    allowGuestRegistration: true,
    requiresPayment: true,
    title: "City Meetup Series",
    talkTitle: "Listening to the First Billion Years of the Universe",
    talkSpeaker: "Shouvik Sarkar",
    feeInfo: "Adults: ₹200\nKids under 16: Free",
    verifiedSuccess: {
      message: "Join the WhatsApp group using the link below. We will approve your WhatsApp group request within 2 hours of payment.",
      linkUrl: "https://chat.whatsapp.com/JtJfoiZ2j7EK5skODJ8mz2",
      linkLabel: "Join WhatsApp Group",
    },
    sheetTab: "August 2 Entries",
    sumAtMost: {
      fields: ["adultParticipants", "kidParticipants"],
      max: 3,
      when: { field: "bringingParticipants", value: "yes" },
      message: "You can bring at most 3 additional participants per registration.",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number (used to add you to the WhatsApp group)",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        helperText: "Maximum 3 additional participants per registration (4 people total).",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (16+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 3 },
        placeholder: "0–3",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<16 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 3 },
        placeholder: "0–3",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "upiReferenceLast4",
        label: "Complete payment, then enter the last 4 digits of your transaction ID",
        helperText: "Pay INR 200 per adult via UPI (kids under 16 are free) — scan the QR code or copy the UPI ID below.",
        copyableValue: "sivasubramanyamicici@ybl",
        copyableLabel: "UPI ID",
        helperImageUrl: "/payment/phonepe-qr.png",
        helperImageAlt: "PhonePe QR code for SIVASUBRAMANYAM A",
        fullWidth: true,
        type: "text",
        required: true,
        validation: {
          pattern: "^\\d{4}$",
          message: "Enter exactly 4 digits",
        },
        placeholder: "e.g. 1234",
        section: "Payment Details",
      },
    ],
  },
  {
    id: "perseids-2026",
    ...FORM_REGISTRATION_WINDOWS["perseids-2026"],
    requiresPayment: false,
    skipCapacityCheck: true,
    allowsRegistrationWhitelist: true,
    registrationClosedMessage:
      "Registration for the Perseids Meteor Shower - 2026 has closed. If you need assistance, please contact us at hello@chennaiastronomyclub.org.",
    title: "Perseids Meteor Shower - 2026",
    description:
      "Register for the Perseids meteor shower overnight session — 12 August 9:00 PM to 13 August 6:00 AM.\n\nOnly night snacks and morning light refreshments (tea + snacks) are provided; please have dinner before arriving at the venue.",
    feeInfo: "Adults: ₹1200\nKids under 12: ₹850",
    sheetTab: "Perseids Entries",
    additionalParticipants: {
      when: { field: "bringingParticipants", value: "yes" },
      adultField: "adultParticipants",
      kidField: "kidParticipants",
      maxAdults: 1,
      maxKids: 2,
      maxTotal: 2,
      messageBoth:
        "You can bring at most 2 additional participants: 1 adult, 1 adult + 1 child, or up to 2 children.",
      messageNone: "Enter the number of additional participants you are bringing.",
      messageTooManyAdults: "You can bring at most 1 additional adult.",
      messageTooManyKids: "You can bring at most 2 additional children.",
    },
    verifiedSuccess: {
      message:
        "As a regular participant, we are skipping the shortlist process for you. You can join the event WhatsApp group directly!",
      linkUrl: "https://chat.whatsapp.com/LqY4exfezmDF0xwc30NWy2?s=cl&p=i&ilr=4",
      linkLabel: "Join WhatsApp Group",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "age",
        label: "Age Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${AGE_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
        options: [
          { label: "Below 18", value: "Below 18" },
          { label: "18 - 25", value: "18-25" },
          { label: "26 - 35", value: "26-35" },
          { label: "36 - 50", value: "36-50" },
          { label: "51 - 65", value: "51-65" },
          { label: "Above 65", value: "Above 65" },
        ],
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label:
          "Number of additional adults (12+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 1 },
        placeholder: "Enter 0 if no additional adults (max 1)",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label:
          "Number of additional children (<12 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 2 },
        placeholder: "Enter 0 if no children (max 2)",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "equipment",
        label: "Equipment that you will bring",
        type: "textarea",
        fullWidth: true,
        section: "Equipment Details",
        placeholder:
          "List any telescopes, binoculars, or other astronomy equipment you plan to bring...",
      },
      {
        name: "canBringCar",
        label: "Can you bring a car and offer carpooling to other participants?",
        type: "select",
        required: true,
        section: "Car Pooling",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "carSeats",
        label: "Number of seats available for other participants",
        type: "number",
        validation: { min: 1, max: 7 },
        placeholder: "How many people can you accommodate?",
        section: "Car Pooling",
        showWhen: { field: "canBringCar", value: "yes" },
      },
      {
        name: "location",
        label: "Where will you be coming from?",
        type: "text",
        required: true,
        placeholder: "Your locality in the city",
        section: "Car Pooling",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Person and Number",
        type: "text",
        required: true,
        discourseField: `user_fields.${EMERGENCY_CONTACT_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        placeholder: "Name & phone number",
        section: "Emergency Information",
      },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${BLOOD_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Emergency Information",
        options: [
          { label: "A+", value: "A+" },
          { label: "A-", value: "A-" },
          { label: "B+", value: "B+" },
          { label: "B-", value: "B-" },
          { label: "AB+", value: "AB+" },
          { label: "AB-", value: "AB-" },
          { label: "O+", value: "O+" },
          { label: "O-", value: "O-" },
        ],
      },
      {
        name: "observationalSkills",
        label: "Describe your observational skills and experience",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder:
          "Tell us about your experience with astronomy and observation...",
      },
      {
        name: "eventReason",
        label: "Why do you want to attend this event?",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Share your motivation for attending...",
      },
      {
        name: "additionalQuestions",
        label: "Anything else that you would like to ask the CAC team?",
        type: "textarea",
        fullWidth: true,
        section: "Additional Questions",
        placeholder: "Any questions for us?",
      },
      {
        name: "conductCode",
        label:
          "I acknowledge that smoking, consuming alcohol and other anti-social behavior are strictly prohibited",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
      {
        name: "riskDisclaimer",
        label:
          "I understand and agree: Travelling by road involves inherent dangers including but not limited to accidents. CAC and its organizers are not responsible for any accidents or injuries during the event. CAC and organizers are not responsible for any loss or damage to personal property. I agree to take full responsibility.",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
    ],
  },
  {
    id: "city-meetup-july-4",
    ...FORM_REGISTRATION_WINDOWS["city-meetup-july-4"],
    allowGuestRegistration: true,
    requiresPayment: true,
    title: "City Meetup Series",
    talkTitle: "The Multilingual Universe",
    talkSpeaker: "Dr Sushant Raut, KREA University",
    feeInfo: "INR 200 per head (venue charges split among all participants)",
    verifiedSuccess: {
      message: "Join the WhatsApp group using the link below. We will approve your WhatsApp group request within 2 hours of payment.",
      linkUrl: "https://chat.whatsapp.com/KHEz08RQNU5GvOfVEHOK90?mode=gi_t",
      linkLabel: "Join WhatsApp Group",
    },
    sheetTab: "July 4 Entries",
    sumAtMost: {
      fields: ["adultParticipants", "kidParticipants"],
      max: 2,
      when: { field: "bringingParticipants", value: "yes" },
      message: "You can bring at most 2 additional participants per registration.",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number (used to add you to the WhatsApp group)",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        helperText: "Maximum 2 additional participants per registration.",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (12+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 2 },
        placeholder: "0, 1, or 2",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<12 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 2 },
        placeholder: "0, 1, or 2",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "upiReferenceLast4",
        label: "Complete payment, then enter the last 4 digits of your transaction ID",
        helperText: "Pay INR 200 per head via UPI — scan the QR code or copy the UPI ID below.",
        copyableValue: "sivasubramanyamicici@ybl",
        copyableLabel: "UPI ID",
        helperImageUrl: "/payment/phonepe-qr.png",
        helperImageAlt: "PhonePe QR code for SIVASUBRAMANYAM A",
        fullWidth: true,
        type: "text",
        required: true,
        validation: {
          pattern: "^\\d{4}$",
          message: "Enter exactly 4 digits",
        },
        placeholder: "e.g. 1234",
        section: "Payment Details",
      },
    ],
  },
  {
    id: "visual-astronomy-june-2026",
    ...FORM_REGISTRATION_WINDOWS["visual-astronomy-june-2026"],
    requiresPayment: false,
    title: "First Light: Beginners' Visual Astronomy Workshop",
    eventInfoLink: {
      message: "Please read the event details before registering.",
      url: "https://forum.chennaiastronomyclub.org/t/first-light-beginners-workshop-on-visual-astronomy/",
      linkLabel: "Event details - Please read before registering",
    },
    feeInfo: "Limited to 15 slots. Costs shared among participants - Rs. 2000 per head",
    sheetTab: "June 13 Entries",
    additionalParticipants: {
      when: { field: "bringingParticipants", value: "yes" },
      adultField: "adultParticipants",
      kidField: "kidParticipants",
      maxAdults: 1,
      maxKids: 2,
      messageBoth:
        "Allowed combinations: 1 adult, 1 child, or 2 children — enter counts in only one column.",
      messageNone: "Enter the number of additional participants you are bringing.",
      messageTooManyAdults: "You can bring at most 1 additional adult.",
      messageTooManyKids: "You can bring at most 2 additional children.",
    },
    verifiedSuccess: {
      message:
        "As a regular participant, we are skipping the shortlist process for you. You can join the event WhatsApp group directly!",
      linkUrl: "https://chat.whatsapp.com/I4KjcLon7sB9SIGtscNa9F?s=cl&p=i&ilr=0",
      linkLabel: "Join WhatsApp Group",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "age",
        label: "Age Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${AGE_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
        options: [
          { label: "Below 18", value: "Below 18" },
          { label: "18 - 25", value: "18-25" },
          { label: "26 - 35", value: "26-35" },
          { label: "36 - 50", value: "36-50" },
          { label: "51 - 65", value: "51-65" },
          { label: "Above 65", value: "Above 65" },
        ],
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        helperText: "Allowed: 1 adult, 1 child, or 2 children.",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (12+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 1 },
        placeholder: "0 or 1",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<12 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 2 },
        placeholder: "0, 1, or 2",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "equipment",
        label: "Equipment that you will bring",
        type: "textarea",
        fullWidth: true,
        section: "Equipment Details",
        placeholder: "List any telescopes, binoculars, or other astronomy equipment you plan to bring...",
      },
      {
        name: "canBringCar",
        label: "Can you bring a car and offer carpooling to other participants?",
        type: "select",
        required: true,
        section: "Car Pooling",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "carSeats",
        label: "Number of seats available for other participants",
        type: "number",
        validation: { min: 1, max: 7 },
        placeholder: "How many people can you accommodate?",
        section: "Car Pooling",
        showWhen: { field: "canBringCar", value: "yes" },
      },
      {
        name: "location",
        label: "Where will you be coming from?",
        type: "text",
        required: true,
        placeholder: "Your locality in the city",
        section: "Car Pooling",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Person and Number",
        type: "text",
        required: true,
        discourseField: `user_fields.${EMERGENCY_CONTACT_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        placeholder: "Name & phone number",
        section: "Emergency Information",
      },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${BLOOD_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Emergency Information",
        options: [
          { label: "A+", value: "A+" },
          { label: "A-", value: "A-" },
          { label: "B+", value: "B+" },
          { label: "B-", value: "B-" },
          { label: "AB+", value: "AB+" },
          { label: "AB-", value: "AB-" },
          { label: "O+", value: "O+" },
          { label: "O-", value: "O-" },
        ],
      },
      {
        name: "observationalSkills",
        label: "What is your experience with astronomy and stargazing?",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Tell us about your experience with astronomy and stargazing...",
      },
      {
        name: "eventReason",
        label: "Why do you want to attend this event?",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Share your motivation for attending...",
      },
      {
        name: "additionalQuestions",
        label: "Anything else that you would like to ask the CAC team?",
        type: "textarea",
        fullWidth: true,
        section: "Additional Questions",
        placeholder: "Any questions for us?",
      },
      {
        name: "conductCode",
        label: "I acknowledge that smoking, consuming alcohol and other anti-social behavior are strictly prohibited",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
      {
        name: "riskDisclaimer",
        label: "I understand and agree: Travelling by road involves inherent dangers including but not limited to accidents. CAC and its organizers are not responsible for any accidents or injuries during the event. CAC and organizers are not responsible for any loss or damage to personal property. I agree to take full responsibility.",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
    ],
  },
  {
    id: "city-meetup-may-31",
    ...FORM_REGISTRATION_WINDOWS["city-meetup-may-31"],
    requiresPayment: true,
    title: "City Meetup Series",
    talkTitle: "Studying Undead Stars to Understand Theories of Physics",
    talkSpeaker: "Prof. Manjari Bagchi, IMSc",
    feeInfo: "INR 200 per head (venue charges split among all participants)",
    verifiedSuccess: {
      message: "Join the WhatsApp group using the link below. We will approve your WhatsApp group request within 2 hours of payment.",
      linkUrl: "https://chat.whatsapp.com/GNTShIlHUvlDY2fQIds4bR?mode=gi_t",
      linkLabel: "Join WhatsApp Group",
    },
    sheetTab: "May 31 Entries",
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number (used to add you to the WhatsApp group)",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "upiReferenceLast4",
        label: "Complete payment, then enter the last 4 digits of your transaction ID",
        helperText: "Pay INR 200 via UPI — scan the QR code or copy the UPI ID below.",
        copyableValue: "sivasubramanyamicici@ybl",
        copyableLabel: "UPI ID",
        helperImageUrl: "/payment/phonepe-qr.png",
        helperImageAlt: "PhonePe QR code for SIVASUBRAMANYAM A",
        fullWidth: true,
        type: "text",
        required: true,
        validation: {
          pattern: "^\\d{4}$",
          message: "Enter exactly 4 digits",
        },
        placeholder: "e.g. 1234",
        section: "Payment Details",
      },
    ],
  },
  {
    id: "star-party-march-2026",
    ...FORM_REGISTRATION_WINDOWS["star-party-march-2026"],
    requiresPayment: false,
    title: "Star Party - March 2026",
    description: "Register your attendance for this month's star party. We are running a two night event on 13th and 14th March, so please specify which night(s) you will be joining. This will help us with logistics and planning.",
    sheetTab: "Entries",
    verifiedSuccess: {
      message: "As a regular participant, we are skipping the shortlist process for you. You can join the event WhatsApp group directly!",
      linkUrl: "https://chat.whatsapp.com/IpR00eMJfD8Cgc6Z54UJIc?mode=gi_t",
      linkLabel: "Join WhatsApp Group",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "age",
        label: "Age Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${AGE_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
        options: [
          { label: "Below 18", value: "Below 18" },
          { label: "18 - 25", value: "18-25" },
          { label: "26 - 35", value: "26-35" },
          { label: "36 - 50", value: "36-50" },
          { label: "51 - 65", value: "51-65" },
          { label: "Above 65", value: "Above 65" },
        ],
      },
      {
        name: "nights",
        label: "Which nights will you be joining?",
        type: "checkbox-group",
        required: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Night 1 — 13th March", value: "13 March" },
          { label: "Night 2 — 14th March", value: "14 March" },
        ],
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (12+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 20 },
        placeholder: "Enter 0 if no additional adults",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<12 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 20 },
        placeholder: "Enter 0 if no children",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "equipment",
        label: "Equipment that you will bring",
        type: "textarea",
        fullWidth: true,
        section: "Equipment Details",
        placeholder: "List any telescopes, binoculars, or other astronomy equipment you plan to bring...",
      },
      {
        name: "canBringCar",
        label: "Can you bring a car and offer carpooling to other participants?",
        type: "select",
        required: true,
        section: "Car Pooling",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "carSeats",
        label: "Number of seats available for other participants",
        type: "number",
        validation: { min: 1, max: 7 },
        placeholder: "How many people can you accommodate?",
        section: "Car Pooling",
        showWhen: { field: "canBringCar", value: "yes" },
      },
      {
        name: "location",
        label: "Where will you be coming from?",
        type: "text",
        required: true,
        placeholder: "Your locality in the city",
        section: "Car Pooling",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Person and Number",
        type: "text",
        required: true,
        discourseField: `user_fields.${EMERGENCY_CONTACT_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        placeholder: "Name & phone number",
        section: "Emergency Information",
      },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${BLOOD_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Emergency Information",
        options: [
          { label: "A+", value: "A+" },
          { label: "A-", value: "A-" },
          { label: "B+", value: "B+" },
          { label: "B-", value: "B-" },
          { label: "AB+", value: "AB+" },
          { label: "AB-", value: "AB-" },
          { label: "O+", value: "O+" },
          { label: "O-", value: "O-" },
        ],
      },
      {
        name: "observationalSkills",
        label: "Describe your observational skills and experience",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Tell us about your experience with astronomy and observation...",
      },
      {
        name: "eventReason",
        label: "Why do you want to attend this event?",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Share your motivation for attending...",
      },
      {
        name: "additionalQuestions",
        label: "Anything else that you would like to ask the CAC team?",
        type: "textarea",
        fullWidth: true,
        section: "Additional Questions",
        placeholder: "Any questions for us?",
      },
      {
        name: "conductCode",
        label: "I acknowledge that smoking, consuming alcohol and other anti-social behavior are strictly prohibited",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
      {
        name: "riskDisclaimer",
        label: "I understand and agree: Travelling by road involves inherent dangers including but not limited to accidents. CAC and its organizers are not responsible for any accidents or injuries during the event. CAC and organizers are not responsible for any loss or damage to personal property. I agree to take full responsibility.",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
    ],
  }, {
    id: "star-party-april-2026",
    ...FORM_REGISTRATION_WINDOWS["star-party-april-2026"],
    requiresPayment: false,
    title: "Star Party - April 2026",
    description: "Register your attendance for April's one-night star party on 11th April. AC rooms available; no individual beds; guests will need to share sleeping space; separate rooms for boys and girls. Adult cost: 1500; child cost: 1100.",
    sheetTab: "April Entries",
    verifiedSuccess: {
      message: "As a regular participant, we are skipping the shortlist process for you. You can join the event WhatsApp group directly!",
      linkUrl: "https://chat.whatsapp.com/LIwgncmAG3uFHVJnMF4zNl?mode=gi_t",
      linkLabel: "Join WhatsApp Group",
    },
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Personal Information",
      },
      {
        name: "phone",
        label: "Contact Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
      },
      {
        name: "age",
        label: "Age Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${AGE_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Personal Information",
        options: [
          { label: "Below 18", value: "Below 18" },
          { label: "18 - 25", value: "18-25" },
          { label: "26 - 35", value: "26-35" },
          { label: "36 - 50", value: "36-50" },
          { label: "51 - 65", value: "51-65" },
          { label: "Above 65", value: "Above 65" },
        ],
      },
      {
        name: "bringingParticipants",
        label: "Will you bring additional participants besides yourself?",
        type: "radio",
        required: true,
        uiOnly: true,
        fullWidth: true,
        section: "Event Attendance",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "adultParticipants",
        label: "Number of additional adults (12+ years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 20 },
        placeholder: "Enter 0 if no additional adults",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "kidParticipants",
        label: "Number of additional children (<12 years) joining with you (excluding the main participant)",
        type: "number",
        required: true,
        validation: { min: 0, max: 20 },
        placeholder: "Enter 0 if no children",
        section: "Event Attendance",
        showWhen: { field: "bringingParticipants", value: "yes" },
      },
      {
        name: "equipment",
        label: "Equipment that you will bring",
        type: "textarea",
        fullWidth: true,
        section: "Equipment Details",
        placeholder: "List any telescopes, binoculars, or other astronomy equipment you plan to bring...",
      },
      {
        name: "canBringCar",
        label: "Can you bring a car and offer carpooling to other participants?",
        type: "select",
        required: true,
        section: "Car Pooling",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        name: "carSeats",
        label: "Number of seats available for other participants",
        type: "number",
        validation: { min: 1, max: 7 },
        placeholder: "How many people can you accommodate?",
        section: "Car Pooling",
        showWhen: { field: "canBringCar", value: "yes" },
      },
      {
        name: "location",
        label: "Where will you be coming from?",
        type: "text",
        required: true,
        placeholder: "Your locality in the city",
        section: "Car Pooling",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Person and Number",
        type: "text",
        required: true,
        discourseField: `user_fields.${EMERGENCY_CONTACT_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        placeholder: "Name & phone number",
        section: "Emergency Information",
      },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${BLOOD_GROUP_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Emergency Information",
        options: [
          { label: "A+", value: "A+" },
          { label: "A-", value: "A-" },
          { label: "B+", value: "B+" },
          { label: "B-", value: "B-" },
          { label: "AB+", value: "AB+" },
          { label: "AB-", value: "AB-" },
          { label: "O+", value: "O+" },
          { label: "O-", value: "O-" },
        ],
      },
      {
        name: "observationalSkills",
        label: "Describe your observational skills and experience",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Tell us about your experience with astronomy and observation...",
      },
      {
        name: "eventReason",
        label: "Why do you want to attend this event?",
        type: "textarea",
        required: true,
        skipForVerified: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Share your motivation for attending...",
      },
      {
        name: "additionalQuestions",
        label: "Anything else that you would like to ask the CAC team?",
        type: "textarea",
        fullWidth: true,
        section: "Additional Questions",
        placeholder: "Any questions for us?",
      },
      {
        name: "conductCode",
        label: "I acknowledge that smoking, consuming alcohol and other anti-social behavior are strictly prohibited",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
      {
        name: "riskDisclaimer",
        label: "I understand and agree: Travelling by road involves inherent dangers including but not limited to accidents. CAC and its organizers are not responsible for any accidents or injuries during the event. CAC and organizers are not responsible for any loss or damage to personal property. I agree to take full responsibility.",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
    ],
  },
  {
    id: "night-sky-passport-presale",
    ...FORM_REGISTRATION_WINDOWS["night-sky-passport-presale"],
    requiresPayment: false,
    title: "Night Sky Passport Presale Registration",
    description: "Register your presale request for Night Sky Passport book copies. This would help us plan the production and distribution of the book.",
    sheetTab: "Night Sky Passport Presale Entries",
    atLeastOneOf: {
      fields: ["adultCopies", "kidsCopies"],
      message: "Enter copies for adults or kids",
    },
    submitLabel: "Submit",
    fields: [
      {
        name: "name",
        label: "Full Name",
        type: "text",
        required: true,
        discourseField: "name",
        verifiedReadOnly: true,
        section: "Contact Information",
      },
      {
        name: "email",
        label: "Email ID",
        type: "email",
        required: true,
        discourseField: "email",
        verifiedReadOnly: true,
        section: "Contact Information",
      },
      {
        name: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        discourseField: `user_fields.${PHONE_FIELD_ID}`,
        verifiedReadOnly: true,
        saveToProfile: true,
        section: "Contact Information",
      },
      {
        name: "adultCopies",
        label: "Number of copies for adults (₹300 each)",
        type: "number",
        required: false,
        validation: { min: 0, max: 100 },
        section: "Presale Details",
        fullWidth: true,
      },
      {
        name: "kidsCopies",
        label: "Number of copies for kids (₹250 each)",
        type: "number",
        required: false,
        validation: { min: 0, max: 100 },
        section: "Presale Details",
        fullWidth: true,
      },
    ],
  },
  {
    id: "visual-astronomy-june-2026-backfill",
    title: "First Light Workshop — Complete Your Registration",
    description:
      "You are already registered for the June 13 workshop. Please fill in the missing details below so we can complete your registration record.",
    sheetTab: "June 13 Entries",
    hiddenFromListing: true,
    updateExistingRegistration: true,
    ...FORM_REGISTRATION_WINDOWS["visual-astronomy-june-2026-backfill"],
    submitLabel: "Save Details",
    fields: [
      {
        name: "location",
        label: "Where will you be coming from?",
        type: "text",
        required: true,
        placeholder: "Your locality in the city",
        section: "Car Pooling",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Person and Number",
        type: "text",
        required: true,
        discourseField: `user_fields.${EMERGENCY_CONTACT_FIELD_ID}`,
        saveToProfile: true,
        placeholder: "Name & phone number",
        section: "Emergency Information",
      },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        required: true,
        discourseField: `user_fields.${BLOOD_GROUP_FIELD_ID}`,
        saveToProfile: true,
        section: "Emergency Information",
        options: [
          { label: "A+", value: "A+" },
          { label: "A-", value: "A-" },
          { label: "B+", value: "B+" },
          { label: "B-", value: "B-" },
          { label: "AB+", value: "AB+" },
          { label: "AB-", value: "AB-" },
          { label: "O+", value: "O+" },
          { label: "O-", value: "O-" },
        ],
      },
      {
        name: "observationalSkills",
        label: "What is your experience with astronomy and stargazing?",
        type: "textarea",
        required: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Tell us about your experience with astronomy and stargazing...",
      },
      {
        name: "eventReason",
        label: "Why do you want to attend this event?",
        type: "textarea",
        required: true,
        fullWidth: true,
        section: "Motivation & Interest",
        placeholder: "Share your motivation for attending...",
      },
      {
        name: "additionalQuestions",
        label: "Anything else that you would like to ask the CAC team?",
        type: "textarea",
        fullWidth: true,
        section: "Additional Questions",
        placeholder: "Any questions for us?",
      },
      {
        name: "conductCode",
        label:
          "I acknowledge that smoking, consuming alcohol and other anti-social behavior are strictly prohibited",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
      {
        name: "riskDisclaimer",
        label:
          "I understand and agree: Travelling by road involves inherent dangers including but not limited to accidents. CAC and its organizers are not responsible for any accidents or injuries during the event. CAC and organizers are not responsible for any loss or damage to personal property. I agree to take full responsibility.",
        type: "checkbox",
        required: true,
        fullWidth: true,
        section: "Disclaimer",
      },
    ],
  },
];

export function getFormConfig(formId: string): FormConfig | undefined {
  return formConfigs.find((f) => f.id === formId);
}

export function allowsGuestRegistration(formId: string): boolean {
  return Boolean(getFormConfig(formId)?.allowGuestRegistration);
}

export function getListedFormConfigs(): FormConfig[] {
  return formConfigs.filter((f) => !f.hiddenFromListing);
}

/**
 * Compute whether registration is currently open, not yet open, or closed
 * based on the form's registrationOpensAt / registrationClosesAt timestamps (IST).
 * If neither is set, registration is always open.
 */
export function getRegistrationStatus(config: FormConfig): RegistrationStatus {
  return getWindowRegistrationStatus(config);
}

/** True once the event's endTime has passed. Forms without endTime are never over. */
export function isEventOver(config: FormConfig): boolean {
  return isWindowEventOver(config);
}

/** Default form for the attendance check-in page (next upcoming listed event). */
export function getDefaultAttendanceFormId(): string {
  const listed = getListedFormConfigs();
  const now = new Date();

  const upcoming = listed
    .filter((f) => f.startTime && parseIstDateTime(f.startTime) >= now)
    .sort(
      (a, b) =>
        parseIstDateTime(a.startTime!).getTime() - parseIstDateTime(b.startTime!).getTime()
    );
  if (upcoming.length > 0) return upcoming[0].id;

  const notOver = listed.filter((f) => !isEventOver(f));
  if (notOver.length > 0) return notOver[0].id;

  return listed[0]?.id ?? "";
}
